package model;
// Generated 24/12/2012 17:12:09 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Avioes generated by hbm2java
 */
public class Avioes  implements java.io.Serializable {


     private int codigo;
     private String marca;
     private Date dataManut;
     private String descricao;
     private Date anoFab;
     private Set viagenses = new HashSet(0);
     private Set aulases = new HashSet(0);

    public Avioes() {
    }

	
    public Avioes(int codigo, String marca, Date dataManut, String descricao, Date anoFab) {
        this.codigo = codigo;
        this.marca = marca;
        this.dataManut = dataManut;
        this.descricao = descricao;
        this.anoFab = anoFab;
    }
    public Avioes(int codigo, String marca, Date dataManut, String descricao, Date anoFab, Set viagenses, Set aulases) {
       this.codigo = codigo;
       this.marca = marca;
       this.dataManut = dataManut;
       this.descricao = descricao;
       this.anoFab = anoFab;
       this.viagenses = viagenses;
       this.aulases = aulases;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Date getDataManut() {
        return this.dataManut;
    }
    
    public void setDataManut(Date dataManut) {
        this.dataManut = dataManut;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getAnoFab() {
        return this.anoFab;
    }
    
    public void setAnoFab(Date anoFab) {
        this.anoFab = anoFab;
    }
    public Set getViagenses() {
        return this.viagenses;
    }
    
    public void setViagenses(Set viagenses) {
        this.viagenses = viagenses;
    }
    public Set getAulases() {
        return this.aulases;
    }
    
    public void setAulases(Set aulases) {
        this.aulases = aulases;
    }

    @Override
    public String toString(){
        return codigo + " - " + marca + " - " + descricao;
    }


}


