package model;
// Generated 24/12/2012 17:12:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private String endereco;
     private String telefone;
     private Set viagenses = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(int codigo, String nome, String endereco, String telefone) {
        this.codigo = codigo;
        this.nome = nome;
        this.endereco = endereco;
        this.telefone = telefone;
    }
    public Clientes(int codigo, String nome, String endereco, String telefone, Set viagenses) {
       this.codigo = codigo;
       this.nome = nome;
       this.endereco = endereco;
       this.telefone = telefone;
       this.viagenses = viagenses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Set getViagenses() {
        return this.viagenses;
    }
    
    public void setViagenses(Set viagenses) {
        this.viagenses = viagenses;
    }

    @Override
    public String toString(){
        return codigo + " - " + nome;
    }



}


