package model;
// Generated 24/12/2012 17:12:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Instrutores generated by hbm2java
 */
public class Instrutores  implements java.io.Serializable {


     private int breve;
     private Pilotos pilotos;
     private Set aulases = new HashSet(0);

    public Instrutores() {
    }

	
    public Instrutores(int breve, Pilotos pilotos) {
        this.breve = breve;
        this.pilotos = pilotos;
    }
    public Instrutores(int breve, Pilotos pilotos, Set aulases) {
       this.breve = breve;
       this.pilotos = pilotos;
       this.aulases = aulases;
    }
   
    public int getBreve() {
        return this.breve;
    }
    
    public void setBreve(int breve) {
        this.breve = breve;
    }
    public Pilotos getPilotos() {
        return this.pilotos;
    }
    
    public void setPilotos(Pilotos pilotos) {
        this.pilotos = pilotos;
    }
    public Set getAulases() {
        return this.aulases;
    }
    
    public void setAulases(Set aulases) {
        this.aulases = aulases;
    }



}


