package model;
// Generated 24/12/2012 17:12:09 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viagens generated by hbm2java
 */
public class Viagens  implements java.io.Serializable {


     private int codigo;
     private Avioes avioes;
     private Clientes clientes;
     private Date dataSaida;
     private Date dataChegada;
     private String cidadeDe;
     private String cidadeAte;
     private float valor;
     private Set pilotoses = new HashSet(0);

    public Viagens() {
    }

	
    public Viagens(int codigo, Avioes avioes, Clientes clientes, Date dataSaida, Date dataChegada, String cidadeDe, String cidadeAte, float valor) {
        this.codigo = codigo;
        this.avioes = avioes;
        this.clientes = clientes;
        this.dataSaida = dataSaida;
        this.dataChegada = dataChegada;
        this.cidadeDe = cidadeDe;
        this.cidadeAte = cidadeAte;
        this.valor = valor;
    }
    public Viagens(int codigo, Avioes avioes, Clientes clientes, Date dataSaida, Date dataChegada, String cidadeDe, String cidadeAte, float valor, Set pilotoses) {
       this.codigo = codigo;
       this.avioes = avioes;
       this.clientes = clientes;
       this.dataSaida = dataSaida;
       this.dataChegada = dataChegada;
       this.cidadeDe = cidadeDe;
       this.cidadeAte = cidadeAte;
       this.valor = valor;
       this.pilotoses = pilotoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Avioes getAvioes() {
        return this.avioes;
    }
    
    public void setAvioes(Avioes avioes) {
        this.avioes = avioes;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Date getDataSaida() {
        return this.dataSaida;
    }
    
    public void setDataSaida(Date dataSaida) {
        this.dataSaida = dataSaida;
    }
    public Date getDataChegada() {
        return this.dataChegada;
    }
    
    public void setDataChegada(Date dataChegada) {
        this.dataChegada = dataChegada;
    }
    public String getCidadeDe() {
        return this.cidadeDe;
    }
    
    public void setCidadeDe(String cidadeDe) {
        this.cidadeDe = cidadeDe;
    }
    public String getCidadeAte() {
        return this.cidadeAte;
    }
    
    public void setCidadeAte(String cidadeAte) {
        this.cidadeAte = cidadeAte;
    }
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }
    public Set getPilotoses() {
        return this.pilotoses;
    }
    
    public void setPilotoses(Set pilotoses) {
        this.pilotoses = pilotoses;
    }




}


