package model;
// Generated 24/12/2012 17:12:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Instituicoes generated by hbm2java
 */
public class Instituicoes  implements java.io.Serializable {


     private int codigo;
     private String cidade;
     private String estado;
     private String telefone;
     private String nome;
     private Set cursoses = new HashSet(0);

    public Instituicoes() {
    }

	
    public Instituicoes(int codigo, String cidade, String estado, String nome) {
        this.codigo = codigo;
        this.cidade = cidade;
        this.estado = estado;
        this.nome = nome;
    }
    public Instituicoes(int codigo, String cidade, String estado, String telefone, String nome, Set cursoses) {
       this.codigo = codigo;
       this.cidade = cidade;
       this.estado = estado;
       this.telefone = telefone;
       this.nome = nome;
       this.cursoses = cursoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set cursoses) {
        this.cursoses = cursoses;
    }




}


