package model;
// Generated 24/12/2012 17:12:09 by Hibernate Tools 3.2.1.GA



/**
 * Instrutorescursos generated by hbm2java
 */
public class Instrutorescursos  implements java.io.Serializable {


     private InstrutorescursosId id;
     private Cursos cursos;
     private Pilotos pilotos;

    public Instrutorescursos() {
    }

    public Instrutorescursos(InstrutorescursosId id, Cursos cursos, Pilotos pilotos) {
       this.id = id;
       this.cursos = cursos;
       this.pilotos = pilotos;
    }
   
    public InstrutorescursosId getId() {
        return this.id;
    }
    
    public void setId(InstrutorescursosId id) {
        this.id = id;
    }
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
    public Pilotos getPilotos() {
        return this.pilotos;
    }
    
    public void setPilotos(Pilotos pilotos) {
        this.pilotos = pilotos;
    }




}


